name: CMake CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.18.4'

      - name: Install dependencies (fmt and Doxygen)
        run: sudo apt-get install -y doxygen graphviz

      - name: Create build directory
        run: mkdir build

      - name: List directory contents
        run: ls -la  # This will list the contents of the current directory

      - name: Configure CMake
        run: |
          pwd
          cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Debug
          ls -la build  # Lists contents of the build directory

      - name: Build the project
        run: |
          pwd
          cmake --build build
          ls -la build  # Lists contents of the build directory
      - name: Run tests
        run: |
          pwd
          ls -la
          cd /build
          ls -la
          cd test
          ls -la
          cd Debug
          ./tests

      # - name: Generate Doxygen Documentation
      #   run: |
      #     cd doc
      #     doxygen Doxyfile

      # - name: Upload Doxygen documentation as artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: doxygen-docs
      #     path: docs/html
      #     retention-days: 7
